### ISSUE TITLE
Ошибку выдаёт при npm start

### ISSUE THREAD

**Issue by Developeran** [yegor-sytnyk/movies-list#2]
[npm-debug.txt](https://github.com/yegor-sytnyk/movies-list/files/545090/npm-debug.txt)

How to run your project? Что я делаю не так https://yadi.sk/i/qMzsxM99xLZfT

**Comment by yegor-sytnyk** [comment]
пропробуйте запустить в папке с проектом

npm install

чтобы установить зависимости
